name: Scan with Contrast CLI
description: Perform SAST analysis of a project
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  # workflow_run:
  #     types: [completed]

runs: 
 using: "composite"
 steps: 
    - name: Set up contrast-cli
      run: |
        npm install --location=global @contrast/contrast@3.2.0
    - name: Scan file
      env:
        CT_API_KEY: ${{ secrets.CONTRAST__API__API_KEY }}
        CT_AUTH_TOKEN: ${{ secrets.CONTRAST__API__AUTH_TOKEN }}
        ORG_ID: ${{ secrets.CONTRAST__API__ORGANIZATION_ID }}
        URL: ${{ secrets.CONTRAST__API__URL }}
      run: |
        contrast-cli --scan ./target/${{ inputs.SERVICE_NAME }}-${{ steps.build-service.outputs.version }}.jar \
          --api_key $CT_API_KEY \
          --authorization $CT_AUTH_TOKEN \
          --organization_id $ORG_ID \
          --host $URL \
          --project_name MY-Project \
          --language JAVA --wait_for_scan
